## 판다스 기초

### 판다스 패키지 로드

```python
import pandas as pd
```

In [2]:
import pandas as pd

In [3]:
# DataFrame을 직접 생성할 때 사용. / 실제론 아래와 같이 잘 안함.
raw_data = {
    'name' : ['홍길동', '김철수', '이영희', '박민수', '성유고', '애슐리'],
    'age' : [20, 21, 23, 24, 30, 29],
    'major' : ['데이터분석', '웹개발', '인공지능', '임베디드', '인공지능', '웹개발'],
    'score' : [85, 90, 95, 100, 80, 90]
}

raw_data

{'name': ['홍길동', '김철수', '이영희', '박민수', '성유고', '애슐리'],
 'age': [20, 21, 23, 24, 30, 29],
 'major': ['데이터분석', '웹개발', '인공지능', '임베디드', '인공지능', '웹개발'],
 'score': [85, 90, 95, 100, 80, 90]}

In [4]:
# 일반적으로 DataFrame을 줄여서 df로 변수명 많이 활용
df = pd.DataFrame(raw_data)
df

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   23   인공지능     95
3  박민수   24   임베디드    100
4  성유고   30   인공지능     80
5  애슐리   29    웹개발     90

In [5]:
df.describe()

             age       score
count   6.000000    6.000000
mean   24.500000   90.000000
std     4.135215    7.071068
min    20.000000   80.000000
25%    21.500000   86.250000
50%    23.500000   90.000000
75%    27.750000   93.750000
max    30.000000  100.000000

### 컬럼 선택

In [6]:
# DataFrame에서 필요한 컬럼만 확인 또는 할당(복사)

df['name']

0    홍길동
1    김철수
2    이영희
3    박민수
4    성유고
5    애슐리
Name: name, dtype: str

In [ ]:
# 컬럼 선택의 편의성으로 추가된 방식. 위와 동일
df.name

0    홍길동
1    김철수
2    이영희
3    박민수
4    성유고
5    애슐리
Name: name, dtype: str

- DataFrame에서 하나의 컬럼만 가져오면 `Series` 타입

#### 컬럼(열) 선택

In [8]:
df[['name', 'age']]

  name  age
0  홍길동   20
1  김철수   21
2  이영희   23
3  박민수   24
4  성유고   30
5  애슐리   29

In [ ]:
# .컬럼 선택으로 데이터 프레임 만드는 방법 없음
df.name, df.age

(0    홍길동
 1    김철수
 2    이영희
 3    박민수
 4    성유고
 5    애슐리
 Name: name, dtype: str,
 0    20
 1    21
 2    23
 3    24
 4    30
 5    29
 Name: age, dtype: int64)

#### 로우(행) 선택

In [ ]:
# 인덱스 이름을 기준
df.loc[0]

name       홍길동
age         20
major    데이터분석
score       85
Name: 0, dtype: object

In [ ]:
# 위치번호 기준. 인덱스를 다른 값으로 바꿨을 때 사용하는 방법
df.iloc[0]

name       홍길동
age         20
major    데이터분석
score       85
Name: 0, dtype: object

In [ ]:
# 시리즈의 인덱스로 열의 값을 확인 가능
df.iloc[0]['name']

'홍길동'

In [ ]:
# 슬라이싱으로 여러행 선택.
# 파이썬 슬라이싱 규칙에서 벗어남. ~ 미만으로 적용되지 않음.
df.loc[0:2]

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   23   인공지능     95

In [30]:
df.iloc[0:2]

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90

#### 행 선택, 인덱스행(loc)과 위치값행(iloc) 차이

In [32]:
df2 = pd.DataFrame(raw_data,
                   index=['S0001', 'S0002', 'S0003', 'S0005', 'S0009', 'S0010'])

df2

      name  age  major  score
S0001  홍길동   20  데이터분석     85
S0002  김철수   21    웹개발     90
S0003  이영희   23   인공지능     95
S0005  박민수   24   임베디드    100
S0009  성유고   30   인공지능     80
S0010  애슐리   29    웹개발     90

In [35]:
df2.loc['S0001' : 'S0009']

      name  age  major  score
S0001  홍길동   20  데이터분석     85
S0002  김철수   21    웹개발     90
S0003  이영희   23   인공지능     95
S0005  박민수   24   임베디드    100
S0009  성유고   30   인공지능     80

In [ ]:
# 파이썬 배열 인덱스와 동일
df2.iloc[ : 4]

      name  age  major  score
S0001  홍길동   20  데이터분석     85
S0002  김철수   21    웹개발     90
S0003  이영희   23   인공지능     95
S0005  박민수   24   임베디드    100

- loc는 부여받은 인덱스로 행 선택 및 슬라이싱
- iloc는 원래부터의 위치값(파이썬 배열의 인덱스)과 동일

#### 행과 열 함께 선택

In [39]:
df.loc[0, 'name']

'홍길동'

In [ ]:
# 인덱스를 따로 부여하지 않은 DF에서 행과 열 선택
df.loc[0:2, ['name', 'age']]

  name  age
0  홍길동   20
1  김철수   21
2  이영희   23

In [45]:
# 인덱스를 따로 지정해준 DF에서 행과 열 선택
df2.loc['S0001':'S0003', ['name', 'age']]
df3 = df2.loc['S0001':'S0003', ['name', 'age']]
df3

      name  age
S0001  홍길동   20
S0002  김철수   21
S0003  이영희   23

#### 조건 조회

- SQL WHERE절과 동일

In [46]:
df['score'] >= 90

0    False
1     True
2     True
3     True
4    False
5     True
Name: score, dtype: bool

In [47]:
df[df['score'] >= 90]

  name  age major  score
1  김철수   21   웹개발     90
2  이영희   23  인공지능     95
3  박민수   24  임베디드    100
5  애슐리   29   웹개발     90

- NumPy와 동일한 조건 연산
- 파이썬 : and, or, not 사용
- NumPy, Pandas : `%`, `|`, `~` 사용
- 연산자 우선순위 문제로 각 조건은 반드시 `()` 사용할 것~

In [ ]:
df[(df['score'] > 90) & (df['age'] >= 21)]

  name  age major  score
2  이영희   23  인공지능     95
3  박민수   24  임베디드    100

In [51]:
df[(df['score'] > 90) | (df['age'] <= 21)]

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   23   인공지능     95
3  박민수   24   임베디드    100

#### 컬럼 추가
- 사용하던 DF 이외에 필요한 컬럼이 생길 때 추가

In [52]:
df

  name  age  major  score
0  홍길동   20  데이터분석     85
1  김철수   21    웹개발     90
2  이영희   23   인공지능     95
3  박민수   24   임베디드    100
4  성유고   30   인공지능     80
5  애슐리   29    웹개발     90

In [ ]:
# 80점을 초과하는 학생만 통과
df['pass'] = df['score'] > 80

In [55]:
df

  name  age  major  score   pass
0  홍길동   20  데이터분석     85   True
1  김철수   21    웹개발     90   True
2  이영희   23   인공지능     95   True
3  박민수   24   임베디드    100   True
4  성유고   30   인공지능     80  False
5  애슐리   29    웹개발     90   True

In [56]:
df['score_bonus'] = df['score'] + 5

df

  name  age  major  score   pass  score_bonus
0  홍길동   20  데이터분석     85   True           90
1  김철수   21    웹개발     90   True           95
2  이영희   23   인공지능     95   True          100
3  박민수   24   임베디드    100   True          105
4  성유고   30   인공지능     80  False           85
5  애슐리   29    웹개발     90   True           95

#### 컬럼 수정
- 기존 컬럼 수정

In [ ]:
# 행선택 에서 score_bonus 점수가 100점이 넘는 행만 선택 후 100점으로 수정
df.loc[df['score_bonus']>100, 'score_bonus'] = 100

df

  name  age  major  score   pass  score_bonus
0  홍길동   20  데이터분석     85   True           90
1  김철수   21    웹개발     90   True           95
2  이영희   23   인공지능     95   True          100
3  박민수   24   임베디드    100   True          100
4  성유고   30   인공지능     80  False           85
5  애슐리   29    웹개발     90   True           95

#### 컬럼 삭제
- 불필요한 컬럼은 삭제

In [ ]:
df.drop(columns=['score_bonus']) # 지워진 것처럼만 출력됨.

df

  name  age  major  score   pass  score_bonus
0  홍길동   20  데이터분석     85   True           90
1  김철수   21    웹개발     90   True           95
2  이영희   23   인공지능     95   True          100
3  박민수   24   임베디드    100   True          100
4  성유고   30   인공지능     80  False           85
5  애슐리   29    웹개발     90   True           95

In [ ]:
df.drop(columns=['score_bonus'], inplace=True) # 두번 실행시 에러남

df

  name  age  major  score   pass
0  홍길동   20  데이터분석     85   True
1  김철수   21    웹개발     90   True
2  이영희   23   인공지능     95   True
3  박민수   24   임베디드    100   True
4  성유고   30   인공지능     80  False
5  애슐리   29    웹개발     90   True

#### 행 추가
- 새로운 행 추가 방법

In [72]:
df.loc[6] = ['최지우', 24, '웹개발', 99, True]

df

  name  age  major  score   pass
0  홍길동   20  데이터분석     85   True
1  김철수   21    웹개발     90   True
2  이영희   23   인공지능     95   True
3  박민수   24   임베디드    100   True
4  성유고   30   인공지능     80  False
5  애슐리   29    웹개발     90   True
6  최지우   24    웹개발     99   True

In [75]:
df.loc[7] = ['최지우', 24, '웹개발', 99, None]
df

  name  age  major  score   pass
0  홍길동   20  데이터분석     85   True
1  김철수   21    웹개발     90   True
2  이영희   23   인공지능     95   True
3  박민수   24   임베디드    100   True
4  성유고   30   인공지능     80  False
5  애슐리   29    웹개발     90   True
6  최지우   24    웹개발     99   True
7  최지우   24    웹개발     99   None

In [77]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    8 non-null      str
 1   age     8 non-null      int64
 2   major   8 non-null      str
 3   score   8 non-null      int64
 4   pass    7 non-null      object
dtypes: int64(2), object(1), str(2)
memory usage: 452.0+ bytes

![alt text](image-1.png)
- pass: 7 non-null, 1개가 결측치

#### 데이터 읽기 쓰기
- 일반적으로 CSV 가장 많이 사용, Excel, txt
- DB도 연동 가능

In [ ]:
# .. 하면 부모 폴더로 이동
df_bookstores = pd.read_csv('../data/부산지역서점.csv')

df_bookstores

### csv

,연번,시설명,전화번호,시군구,위도,경도,정렬번호
0,0,동사서독,0507-1396-1606,부산 금정구 금정로 87 2층,35.232421,129.086648,67
1,1,흰돌서점,051-625-9633,부산 수영구 남천서로32번길 38 흰돌서점,35.145707,129.106685,1
2,2,효원도서,051-517-6871,부산 금정구 부산대학로 63 (장전동),35.231481,129.084427,2
3,3,화명서점,051-337-0140,부산 북구 화명신도시로 130 로얄팰리스 110호 화명서점,35.235544,129.011331,3
4,4,현대서점,051-581-7963,부산 금정구 남산로 30 현대서점 (남산동),35.267302,129.088872,4
...,...,...,...,...,...,...,...
62,62,책과아이들,051-506-1448,부산 연제구 교대로16번길 20,35.196453,129.078185,62
63,63,책마을,051-753-8685,부산 연제구 안연로8번길 19 3층,35.188471,129.102055,63
64,64,카프카의 밤,051-665-5516,부산 연제구 고분로191번길 20,35.186167,129.104129,64
65,65,동네책방 아인,051-665-5516,부산 연제구 월드컵대로 221 다우빌딩 2층,35.188866,129.072650,65
66,66,책방 감,051-581-3318,부산 연제구 교대로24번길 10,35.195938,129.077150,66

In [84]:
# 데이터 쓰기
df2.to_csv('../data/학생정보2.csv', encoding='utf-8')

In [85]:
df_bookstores2 = pd.read_excel('../data/부산지역서점.xlsx')

df_bookstores2

,연번,시설명,전화번호,시군구,위도,경도,정렬번호
0,0,동사서독,0507-1396-1606,부산 금정구 금정로 87 2층,35.232421,129.086648,67
1,1,흰돌서점,051-625-9633,부산 수영구 남천서로32번길 38 흰돌서점,35.145707,129.106685,1
2,2,효원도서,051-517-6871,부산 금정구 부산대학로 63 (장전동),35.231481,129.084427,2
3,3,화명서점,051-337-0140,부산 북구 화명신도시로 130 로얄팰리스 110호 화명서점,35.235544,129.011331,3
4,4,현대서점,051-581-7963,부산 금정구 남산로 30 현대서점 (남산동),35.267302,129.088872,4
...,...,...,...,...,...,...,...
62,62,책과아이들,051-506-1448,부산 연제구 교대로16번길 20,35.196453,129.078185,62
63,63,책마을,051-753-8685,부산 연제구 안연로8번길 19 3층,35.188471,129.102055,63
64,64,카프카의 밤,051-665-5516,부산 연제구 고분로191번길 20,35.186167,129.104129,64
65,65,동네책방 아인,051-665-5516,부산 연제구 월드컵대로 221 다우빌딩 2층,35.188866,129.072650,65
66,66,책방 감,051-581-3318,부산 연제구 교대로24번길 10,35.195938,129.077150,66

#### PostgreSQL / DB에서 불러오기

-psycopg

```python
import psycopg
```

In [86]:
import psycopg

In [87]:
conn = psycopg.connect(
    host='localhost',
    port=5432,
    dbname='ai_db',
    user='postgres',
    password='123456'
)

In [95]:
sql = 'select * from students'
df_postgres_students = pd.read_sql(sql, conn)

df_postgres_students

C:\Users\User\AppData\Local\Temp\ipykernel_29688\883500686.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_postgres_students = pd.read_sql(sql, conn)

,id,name,email,age,major,created_at
0,1,김철수,kim@example.com,21,인공지능,2026-09-17 15:51:11.371099
1,2,이영희,lee@example.com,22,데이터분석,2026-09-17 15:51:11.371099
2,3,박민수,park@example.com,23,웹개발,2026-09-17 15:51:11.371099
3,4,최지훈,choi@example.com,24,임베디드,2026-09-17 15:51:11.371099
4,5,정수빈,jung@example.com,20,클라우드,2026-09-17 15:51:11.371099
5,6,주예찬,yeah@naver.com,24,인공지능,2026-09-18 10:36:04.825460
6,7,이찬혁,leeh@naver.com,26,임베디드,2026-09-18 10:36:04.825460
7,13,흥민손,hasdghasdgasdgasdgasdgasdgasdqwerqwerqwerqwerw...,33,축구공,2026-09-22 13:51:23.789007
8,14,김구라,QWER@qwer.CPM,234,기계,2026-09-23 09:12:51.121343
9,15,string,string,0,string,2026-09-23 09:13:26.354182

- PostgreSQL로 데이터 저장은 추후

### 실습
- 상품데이터 활용

In [115]:
data = {
    'product' : ['키보드', '마우스', '모니터', 'USB', '노트북'],
    'category' : ['주변기기', '주변기기', '디스플레이', '저장장치', '컴퓨터'],
    'price' : [30000, 15000, 250000, 12000, 1200000],
    'stock' : [10, 30, 5, 50, 3]
}

df_products = pd.DataFrame(data)

1. 전체 데이터 출력
2. product, price 컬럼 출력
3. 가격이 50000원 이상인 상품만 출력
4. 재고가 10개 이상인 상품만 출력
5. total_value 컬럼 추가, 계산식은 price * stock
6. 전체 재고의 합계 출력
7. 카테고리가 주변기기인 상품만 출력

In [100]:
# 1번
df_products

  product category    price  stock
0     키보드     주변기기    30000     10
1     마우스     주변기기    15000     30
2     모니터    디스플레이   250000      5
3     USB     저장장치    12000     50
4     노트북      컴퓨터  1200000      3

In [101]:
#2번
df_products[['product', 'price']]

  product    price
0     키보드    30000
1     마우스    15000
2     모니터   250000
3     USB    12000
4     노트북  1200000

In [104]:
df_products[df_products['price'] >= 50000]

  product category    price  stock
2     모니터    디스플레이   250000      5
4     노트북      컴퓨터  1200000      3

In [105]:
df_products[df_products['stock'] >= 10]

  product category  price  stock
0     키보드     주변기기  30000     10
1     마우스     주변기기  15000     30
3     USB     저장장치  12000     50

In [117]:
df_products['total_value'] = df_products['price'] * df_products['stock']

df_products

  product category    price  stock  total_value
0     키보드     주변기기    30000     10       300000
1     마우스     주변기기    15000     30       450000
2     모니터    디스플레이   250000      5      1250000
3     USB     저장장치    12000     50       600000
4     노트북      컴퓨터  1200000      3      3600000

In [110]:
df_products.stock.sum()

np.int64(98)

In [119]:
df_products['stock'].sum()

np.int64(98)

In [121]:
df_products[df_products['category'] == '주변기기']

  product category  price  stock  total_value
0     키보드     주변기기  30000     10       300000
1     마우스     주변기기  15000     30       450000

In [123]:
df_products.to_excel('../data/상품정보.xlsx')